project_id = "pjfzsxxftgcnpsarlygy"

[functions.check-youtube-live]
verify_jwt = true

[functions.send-whatsapp]
verify_jwt = true

[functions.send-event-reminders]
verify_jwt = true

[functions.admin-operations]
verify_jwt = false

[functions.temple-chatbot]
verify_jwt = false

[functions.send-security-alert]
verify_jwt = true

[functions.send-booking-notification]
verify_jwt = false

[functions.send-room-booking-notification]
verify_jwt = false

[functions.send-bulk-whatsapp]
verify_jwt = false

[functions.send-low-stock-alerts]
verify_jwt = true

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.reset-password-with-otp]
verify_jwt = false
