import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

interface LowStockItem {
  id: string;
  name: string;
  current_stock: number;
  min_stock_level: number;
  unit: string;
  category: string;
}

Deno.serve(async (req) => {
  // Handle CORS preflight requests
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders });
  }

  try {
    const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
    const supabaseServiceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
    const whatsappToken = Deno.env.get('WHATSAPP_ACCESS_TOKEN');
    const whatsappPhoneId = Deno.env.get('WHATSAPP_PHONE_NUMBER_ID');

    if (!whatsappToken || !whatsappPhoneId) {
      console.error('WhatsApp credentials not configured');
      return new Response(
        JSON.stringify({ success: false, error: 'WhatsApp not configured' }),
        { headers: { ...corsHeaders, 'Content-Type': 'application/json' }, status: 500 }
      );
    }

    const supabase = createClient(supabaseUrl, supabaseServiceKey);

    // Get low stock items from the view
    const { data: lowStockItems, error: stockError } = await supabase
      .from('inventory_stock_balance')
      .select('*')
      .eq('is_low_stock', true)
      .eq('is_active', true);

    if (stockError) {
      console.error('Error fetching low stock items:', stockError);
      throw stockError;
    }

    if (!lowStockItems || lowStockItems.length === 0) {
      console.log('No low stock items found');
      return new Response(
        JSON.stringify({ success: true, message: 'No low stock items', sent: 0 }),
        { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    console.log(`Found ${lowStockItems.length} low stock items`);

    // Build alert message
    const categoryLabels: Record<string, string> = {
      puja_materials: 'Puja Materials',
      food_prasad: 'Food/Prasad',
      other: 'Other',
    };

    let messageBody = `🚨 *LOW STOCK ALERT*\n\nThe following items are below minimum stock level:\n\n`;

    lowStockItems.forEach((item: LowStockItem, index: number) => {
      const category = categoryLabels[item.category] || item.category;
      messageBody += `${index + 1}. *${item.name}*\n`;
      messageBody += `   📦 Current: ${item.current_stock} ${item.unit}\n`;
      messageBody += `   ⚠️ Minimum: ${item.min_stock_level} ${item.unit}\n`;
      messageBody += `   📁 Category: ${category}\n\n`;
    });

    messageBody += `Please restock these items soon.\n\n_Generated by Temple Management System_`;

    // Get admin users' WhatsApp numbers
    const { data: adminRoles, error: rolesError } = await supabase
      .from('user_roles')
      .select('user_id')
      .eq('role', 'admin');

    if (rolesError) {
      console.error('Error fetching admin roles:', rolesError);
      throw rolesError;
    }

    if (!adminRoles || adminRoles.length === 0) {
      console.log('No admin users found');
      return new Response(
        JSON.stringify({ success: true, message: 'No admin users to notify', sent: 0 }),
        { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    const adminUserIds = adminRoles.map((r) => r.user_id);

    // Get WhatsApp numbers for admins
    const { data: subscriptions, error: subError } = await supabase
      .from('notification_subscriptions')
      .select('whatsapp_number')
      .in('user_id', adminUserIds)
      .eq('whatsapp_notifications', true)
      .not('whatsapp_number', 'is', null);

    if (subError) {
      console.error('Error fetching subscriptions:', subError);
      throw subError;
    }

    if (!subscriptions || subscriptions.length === 0) {
      console.log('No admin WhatsApp subscriptions found');
      return new Response(
        JSON.stringify({ success: true, message: 'No admin WhatsApp subscriptions', sent: 0 }),
        { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    let sentCount = 0;
    let failedCount = 0;

    // Send WhatsApp messages to all admin subscribers
    for (const sub of subscriptions) {
      if (!sub.whatsapp_number) continue;

      try {
        const response = await fetch(
          `https://graph.facebook.com/v18.0/${whatsappPhoneId}/messages`,
          {
            method: 'POST',
            headers: {
              Authorization: `Bearer ${whatsappToken}`,
              'Content-Type': 'application/json',
            },
            body: JSON.stringify({
              messaging_product: 'whatsapp',
              to: sub.whatsapp_number.replace(/[^0-9]/g, ''),
              type: 'text',
              text: { body: messageBody },
            }),
          }
        );

        if (response.ok) {
          sentCount++;
          console.log(`Alert sent to ${sub.whatsapp_number}`);
        } else {
          failedCount++;
          const errorData = await response.json();
          console.error(`Failed to send to ${sub.whatsapp_number}:`, errorData);
        }
      } catch (error) {
        failedCount++;
        console.error(`Error sending to ${sub.whatsapp_number}:`, error);
      }

      // Small delay to avoid rate limiting
      await new Promise((resolve) => setTimeout(resolve, 500));
    }

    console.log(`Low stock alerts sent: ${sentCount}, failed: ${failedCount}`);

    return new Response(
      JSON.stringify({
        success: true,
        lowStockCount: lowStockItems.length,
        sent: sentCount,
        failed: failedCount,
      }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  } catch (error) {
    console.error('Error in send-low-stock-alerts:', error);
    const errorMessage = error instanceof Error ? error.message : 'Unknown error';
    return new Response(
      JSON.stringify({ success: false, error: errorMessage }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' }, status: 500 }
    );
  }
});
